import type { VillageSlug } from './villages';

export const exploreSources = {
  umkm: { id: 'local-umkm', title: 'Direktori UMKM Binaan', publisher: 'Diskuktransesdm Kabupaten Karanganyar', year: 'Tahun pendataan tidak tercantum', url: 'https://diskuktransesdm.karanganyarkab.go.id/umkm-binaan/', scope: 'Nama usaha dan alamat di Dagen, Ngringo, dan Sroyo.', kind: 'Potensi' as const, note: 'Pilihan editorial dari direktori resmi, bukan daftar lengkap atau konfirmasi usaha masih beroperasi. Nomor baris dicatat untuk penelusuran. Diperiksa 5 Oktober 2026.' },
  climate: { id: 'local-climate', title: 'Kampung Iklim — Kecamatan Jaten', publisher: 'Dinas Lingkungan Hidup Kabupaten Karanganyar', year: 'Catatan penghargaan 2019', url: 'https://dlh.karanganyarkab.go.id/kampung-iklim/', scope: 'Ngringo tercatat sebagai ProKlim kategori Madya tahun 2019.', kind: 'Potensi' as const, note: 'Catatan historis program lingkungan, bukan objek wisata atau status penghargaan terbaru. Sumber tidak memberikan titik kunjungan. Diperiksa 5 Oktober 2026.' },
  culture: { id: 'local-culture', title: 'Peta Potensi Investasi Karanganyar 2025', publisher: 'Open Data Kabupaten Karanganyar · DPMPTSP', year: 'Publikasi 2025 · halaman PDF 45', url: 'https://opendata.karanganyarkab.go.id/dataset/0da9d288-37d3-46a0-ba2e-72219c3ab276/resource/583be1bd-b3ed-4d21-bdf6-8b53bc1e0432/download/peta-potensi-investasi-kabupaten-karanganyar-2025-compressed.pdf#page=45', scope: 'Guntur Laras di Sroyo, Jaten, dalam bagian karawitan.', kind: 'Potensi' as const, note: 'Publikasi mencantumkan nama kelompok dan desa; tidak mencantumkan alamat sanggar, jadwal pentas, atau kontak. Diperiksa 5 Oktober 2026.' },
};
export type ExploreCategory = 'UMKM' | 'Budaya' | 'Lingkungan';
export type ExploreEntry = { id: string; name: string; village: VillageSlug; category: ExploreCategory; address: string; reference: string; source: keyof typeof exploreSources; description: string };
export const exploreEntries: ExploreEntry[] = [
  { id: 'permak-yani', name: 'Rumah Permak Ibu Yani', village: 'dagen', category: 'UMKM', address: 'Dagen RT 003 RW 010, Jaten', reference: 'Baris 165', source: 'umkm', description: 'Tercantum dalam direktori UMKM binaan kabupaten.' },
  { id: 'kue-mart', name: 'Kue Mbah Mart', village: 'dagen', category: 'UMKM', address: 'Dagen RT 003 RW 010', reference: 'Baris 229', source: 'umkm', description: 'Tercantum dalam direktori UMKM binaan kabupaten.' },
  { id: 'ucika', name: 'Ucika Collection', village: 'ngringo', category: 'UMKM', address: 'Jl. Sawo 4 No. 99, Ngringo, Jaten', reference: 'Baris 209', source: 'umkm', description: 'Tercantum dalam direktori UMKM binaan kabupaten.' },
  { id: 'arrayyan', name: 'Arrayyan Snack', village: 'ngringo', category: 'UMKM', address: 'Karangwuni RT 001 RW 004, Ngringo, Jaten', reference: 'Baris 256', source: 'umkm', description: 'Tercantum dalam direktori UMKM binaan kabupaten.' },
  { id: 'pawon-nur', name: 'Pawon Mb Nur', village: 'sroyo', category: 'UMKM', address: 'Sroyo RT 005 RW 009, Desa Sroyo', reference: 'Baris 240', source: 'umkm', description: 'Tercantum dalam direktori UMKM binaan kabupaten.' },
  { id: 'qiyan', name: 'Qiyan Dimsum', village: 'sroyo', category: 'UMKM', address: 'Sroyo RT 001 RW 009, Jaten', reference: 'Baris 305', source: 'umkm', description: 'Tercantum dalam direktori UMKM binaan kabupaten.' },
  { id: 'guntur-laras', name: 'Guntur Laras', village: 'sroyo', category: 'Budaya', address: 'Sroyo, Jaten · alamat sanggar belum tersedia', reference: 'Halaman PDF 45 · Karawitan', source: 'culture', description: 'Kelompok karawitan yang dicatat dalam publikasi potensi investasi kabupaten tahun 2025.' },
  { id: 'proklim-ngringo', name: 'Kampung Iklim Ngringo', village: 'ngringo', category: 'Lingkungan', address: 'Desa Ngringo, Kecamatan Jaten', reference: 'Tabel Kecamatan Jaten · 2019', source: 'climate', description: 'DLH mencatat Ngringo sebagai ProKlim kategori Madya pada 2019. Jejak partisipasi desa dalam program lingkungan.' },
];
